spring.application.name=voluntarioserca

spring.datasource.url=jdbc:postgresql://localhost:5433/voluntarioserca
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
